apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-http-server
  namespace: dt-metrics-sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-http-server    
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: External
    external:
      metric:
        name: com.dynatrace.builtin:service.responsetime
        selector:
          matchLabels:
            hpa: frontend-http-server
      target:
        type: AverageValue
        value: 1500000000m