name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Compile
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o build/ks-dt-m-a
      - name: Get Tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Docker Image
        run: docker build . --file Dockerfile -t dtcookie/ks-dt-m-a:${{steps.tag.outputs.tag}}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ks-dt-m-a:${{steps.tag.outputs.tag}}
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload YAML artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deploy.yaml
          asset_name: deploy.yaml
          asset_content_type: application/yaml